language: python
python:
    - "2.7"
    # Doesn't work with Suds
    #- "3.5"
install:
    - travis_retry pip install -r requirements.txt
    - travis_retry pip install coveralls
script:
    - nosetests --with-coverage --cover-package=shaibos
after_success:
    - coveralls
