language: python
python:
    - "2.7"
    - "3.5"
install:
    - travis_retry pip install -r requirements.txt
    - travis_retry pip install coveralls
script:
    # Run unit tests
    - nosetests --with-coverage --cover-package=shaibos
    # Try installing
    - python setup.py build install
after_success:
    - coveralls
